### ISSUE TITLE
Unicode error starting FSAL server

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/fsal#12]
This is observed on Lighthouse (1.4.202 dev snapshot) using FSAL @dd2d39ca9096db5ccdb5278c402c078b334552be

```
# fsal --conf /etc/fsal.ini 
DEBUG:root:Using database /mnt/data/fsal/fs.sqlite
DEBUG:root:Connected to database /mnt/data/fsal/fs.sqlite
DEBUG:root:Migration version for None is 3
Traceback (most recent call last):
  File "/usr/bin/fsal", line 9, in <module>
    load_entry_point('fsal==0.0.1', 'console_scripts', 'fsal')()
  File "/usr/lib/python2.7/site-packages/fsal/server.py", line 142, in main
    fs_manager.start()
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 50, in start
    self._refresh_db()
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 183, in _refresh_db
    self._update_db()
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 223, in _update_db
    if os.path.isdir(path):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017e' in position 53: ordinal not in range(128)
```

Doing an `os.stat()` call manually on the folders with non-ASCII names does not raise ascii codec error.

**Comment by goodbadwolf** [comment]
It was triggered due to missing locales on Lighthouse build. Once they were added, it was reported to be running with "blatant coolness"
