### ISSUE TITLE
Raises on SIGTERM

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/fsal#13]
FSAL fails  to trap an `OSError` exception when existing.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/fsal/daemon.py", line 52, in <lambda>
    atexit.register(lambda: os.remove(args.pidfile))
OSError: [Errno 2] No such file or directory: '/var/run/fsal.pid'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/fsal/daemon.py", line 52, in <lambda>
    atexit.register(lambda: os.remove(args.pidfile))
OSError: [Errno 2] No such file or directory: '/var/run/fsal.pid'
```

**Comment by goodbadwolf** [comment]
Resolved in a8390860e4eeddf0c10b413d1048310090271307
