### ISSUE TITLE
Handle file I/O errors more robustly

### ISSUE THREAD

**Issue by goodbadwolf** [Outernet-Project/fsal#16]
Traceback on failed file I/O:

```
Traceback (most recent call last):
  File "/usr/bin/fsal-daemon", line 9, in <module>
    load_entry_point('fsal==0.0.1', 'console_scripts', 'fsal-daemon')()
  File "/usr/lib/python2.7/site-packages/fsal/daemon.py", line 54, in main
    fsal.server.main()
  File "/usr/lib/python2.7/site-packages/fsal/server.py", line 142, in main
    fs_manager.start()
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 50, in start
    self._refresh_db()
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 183, in _refresh_db
    self._update_db()
  File "/usr/lib/python2.7/site-packages/fsal/fsdbmanager.py", line 218, in _update_db
    for path in fnwalk(self.base_path, checker):
  File "/usr/lib/python2.7/site-packages/fsal/utils.py", line 55, in fnwalk
    for child in fnwalk(entry.path, fn, shallow):
  File "/usr/lib/python2.7/site-packages/fsal/utils.py", line 55, in fnwalk
    for child in fnwalk(entry.path, fn, shallow):
  File "/usr/lib/python2.7/site-packages/fsal/utils.py", line 53, in fnwalk
    for entry in entries:
  File "/usr/lib/python2.7/site-packages/scandir.py", line 581, in scandir_c
    for name, d_type in scandir_helper(path):
OSError: [Errno 5] Input/output error: '/mnt/data/downloads/Old content/Austin Osman Spare Wikipedia the free encyclopedia/'
```

**Comment by goodbadwolf** [comment]
Fixed in 58233521f5a83aedcb882cc632b1b9564168ada7
