### ISSUE TITLE
ParseError during importing

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/fsal#18]
During content import from a box with lots of legacy content, FSAL raises ParseError.

```
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/databases/plugins.py", line 11, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/sessions/plugins.py", line 37, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/auth/plugins.py", line 32, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bottle_utils/i18n.py", line 387, in wrapper
    return callback(*args, **kwargs)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/site-packages/librarian_setup/plugins.py", line 18, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_captive/plugins.py", line 27, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_library/plugins.py", line 36, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_setup/routes.py", line 36, in enter_wizard
    return request.app.supervisor.exts.setup_wizard()
  File "/usr/lib/python2.7/site-packages/librarian_setup/wizard.py", line 39, in __call__
    return instance.dispatch()
  File "/usr/lib/python2.7/site-packages/librarian_setup/wizard.py", line 61, in dispatch
    return self.process_current_step()
  File "/usr/lib/python2.7/site-packages/librarian_setup/wizard.py", line 162, in process_current_step
    step_result = step['handler']()
  File "/usr/lib/python2.7/site-packages/librarian_library/setup.py", line 89, in setup_import_content
    import_content(srcdir, destdir, fsal, archive)
  File "/usr/lib/python2.7/site-packages/librarian_library/importer.py", line 133, in import_content
    (success, error) = fsal.transfer(src_path, dest_path)
  File "/usr/lib/python2.7/site-packages/fsal/client.py", line 57, in wrapper
    response_xml = ET.fromstring(response)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
```

**Comment by goodbadwolf** [comment]
I could not reproduce the issues. Will reopen if seen again.
