### ISSUE TITLE
Descriptive error messages for FSAL client

### ISSUE THREAD

**Issue by goodbadwolf** [Outernet-Project/fsal#7]
```
Traceback (most recent call last):
  File "/home/ben/dev/repos/modular-librarian/core/librarian_core/contrib/tasks/scheduler.py", line 35, in _execute
    fn(*args, **kwargs)
  File "/home/ben/dev/repos/modular-librarian/twitter/librarian_twitter/tasks.py", line 8, in check_for_tweets
    for f in manager.list(config['twitter.tweetdir']):
  File "/home/ben/dev/repos/modular-librarian/filemanager/librarian_filemanager/manager.py", line 81, in list
    (dirs, files) = self.fsal_client.list_dir(path)
  File "/home/ben/.envs/modular-librarian/lib/python2.7/site-packages/fsal/client.py", line 46, in wrapper
    response = self._send_request(tostring(request_xml))
  File "/home/ben/.envs/modular-librarian/lib/python2.7/site-packages/fsal/client.py", line 67, in _send_request
    sock.connect(self.socket_path)
  File "/home/ben/.envs/modular-librarian/lib/python2.7/site-packages/gevent/socket.py", line 349, in connect
    raise error(result, strerror(result))
error: [Errno 2] No such file or directory
```

**Comment by goodbadwolf** [comment]
Fixed in 0f0614f234842a97dd3b02db3e5911fdc71b1ef5
